name: Run Tests

on:
  push:
    branches:
      - "main"
    paths:
      # Always run when workflow configs change
      - ".github/workflows/**"
      # Run when package changes
      - "**"
  release:
    types: [published]

  pull_request:
    branches:
      - "main"
    paths:
      # Always run when workflow configs change
      - ".github/workflows/**"
      # Run when package changes
      - "**"

  workflow_dispatch: {}

jobs:
  test_client:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv

      - name: Create virtual environment
        run: |
          uv sync

      - name: Run tests
        working-directory: .
        run: |
          uv run python -m pytest -sv
